(function (root, factory) {
  if (typeof module === "object" && module.exports) module.exports = factory();
  else root.GAME_CONFIG = factory();
})(typeof self !== "undefined" ? self : this, function () {
  return {
    MAP_SIZE: 22000,
    TICK_MS: 50,
    TIME_SCALE: 1,
    SNAPSHOT_EVERY: 1,
    AOI: 2200,
    MAX_PLAYERS: 50,
    BOT_FILL: 50,
    LOBBY_SECONDS: 8,
    ONLINE_WS: "",

    PLAYER_R: 30,
    SHADOW_R: 18,
    SHADOW_RANGE: 118,
    SHADOW_AGGRO: 340,
    GUARD_RADIUS: 160,
    MERGE_CD: 1.1,
    PORTAL_COUNT: 18,
    BOSS_PORTAL_GAP: 1800,
    RANK_COLOR: {
      E: "#5cff9a",
      D: "#4aa3ff",
      C: "#c56bff",
      B: "#e7c56a",
      A: "#ff3355",
      S: "#efe7d6",
    },
    CENTRAL_BOSS: {
      name: "Malakor, Souverain de l'Abîme",
      short: "Malakor",
    },
    BR_BOSS_R: 196,
    MONARCH_R: 196,
    MINI_R: 98,

    DODGE_CD: 4.8,
    DODGE_DIST: 210,
    DODGE_TIME: 0.22,
    DUEL_RANGE: 340,
    DUEL_R_MIN: 250,
    DUEL_R_MAX: 420,
    DUEL_PAD: 160,

    CLASS: {
      novice: {
        speed: 112, hp: 480, armor: 0, rangeBonus: 0,
        bar: 40, color: "#c4b8a4", label: "Novice",
        desc: "Classe de base. Aucun bonus.",
      },
      assassin: {
        speed: 152, hp: 440, armor: 0, rangeBonus: 0,
        bar: 36, color: "#ff3355", label: "Assassin",
        desc: "Se déplace beaucoup plus vite. L’arme équipée ne change pas.",
      },
      tank: {
        speed: 90, hp: 1180, armor: 0.42, rangeBonus: 0,
        bar: 72, color: "#3da6ff", label: "Tank",
        desc: "Beaucoup plus de PV et une armure. L’arme équipée ne change pas.",
      },
      mage: {
        speed: 108, hp: 400, armor: 0, rangeBonus: 96,
        bar: 34, color: "#c56bff", label: "Mage",
        desc: "Lance en boomerang : poings, lance, sabre laser, katana, faux, dagues, masse, marteau. Arc, arbalète, bazooka et pistolet laser se tirent normalement.",
      },
    },

    WEAPONS: {
      novice: { swing: "punch", atk: 9, range: 88, cd: 0.58, label: "Poings" },
      katana: { swing: "slash", atk: 18, range: 118, cd: 0.18, label: "Katana" },
      scythe: { swing: "slash", atk: 17, range: 132, cd: 0.28, label: "Faux" },
      daggers: { swing: "slash", atk: 16, range: 70, cd: 0.12, crit: 0.5, critMul: 2.5, label: "Dagues" },
      spear: { swing: "slash", atk: 16, range: 188, cd: 0.32, lunge: 28, label: "Lance" },
      mace: { swing: "crush", atk: 18, range: 110, cd: 0.7, aoe: 70, label: "Masse" },
      hammer: { swing: "crush", atk: 20, range: 120, cd: 0.82, aoe: 88, knock: 64, label: "Marteau" },
      bow: { swing: "bow", proj: "arrow", atk: 20, range: 250, cd: 0.62, splash: 0, label: "Arc" },
      crossbow: { swing: "bow", proj: "arrow", atk: 22, range: 230, cd: 0.78, splash: 0, label: "Arbalète" },
      bazooka: { swing: "crush", proj: "rocket", atk: 28, range: 210, cd: 1.15, splash: 92, projSpeed: 260, label: "Bazooka" },
      saber: { swing: "slash", atk: 32, range: 148, cd: 0.2, label: "Sabre laser" },
      laser: { swing: "gun", proj: "pulse", atk: 46, range: 330, cd: 0.5, projSpeed: 1100, label: "Pistolet laser" },
    },

    CHEST_COUNT: 88,
    CHEST_WEAPONS: ["katana", "scythe", "daggers", "spear", "mace", "hammer", "bow", "crossbow", "bazooka", "saber", "laser"],
    MAGE_THROW: ["novice", "spear", "saber", "katana", "scythe", "daggers", "mace", "hammer"],
    BUFF_TIME: 16,

    WEAKNESS: {
      wolf: { assassin: 1.15, tank: 0.82, mage: 1.4, novice: 1 },
      goblin: { assassin: 1.5, tank: 1.0, mage: 0.85, novice: 1 },
      beetle: { assassin: 0.78, tank: 1.55, mage: 1.12, novice: 1 },
      wraith: { assassin: 1.22, tank: 0.72, mage: 1.5, novice: 1 },
      knight: { assassin: 1.18, tank: 1.38, mage: 0.8, novice: 1 },
    },

    BARRIER_START: 16200,
    BR_END: 220,
    RAID_ARENA: 1400,
    SHRINK_DELAY: 35,
    ZONE: {
      WAIT: 32,
      MOVE: 24,
      STEPS_BR: [16200, 13200, 10600, 8200, 6000, 4200, 2800, 1700, 900, 220],
      STEPS_RAID: [16200, 13200, 10600, 8200, 6000, 4200, 2800, 1400],
    },

    MONARCH_HP_BASE: 16000,
    MONARCH_HP_PER: 2800,
    MONARCH_ATK: 34,
    MONARCH_POWER: 5,
    BR_BOSS_HP: 28000,
    BR_BOSS_ATK: 42,

    ORB_COUNT: 2880,
    TILE_COUNT: 240,
    MEGA_CUBE_COUNT: 10,
    MEGA_CUBE_TIME: 32,
    MEGA_DMG: 1.75,
    MEGA_SPEED: 1.55,
    MEGA_DR: 0.82,
    MEGA_HEAL: 0.28,
    OBSTACLE_COUNT: 160,
    BIG_ROCK_COUNT: 28,

    MONSTER: {
      wolf: {
        name: "Loup d'ombre", hp: 155, atk: 8, r: 22, speed: 78, aggro: 260,
        behavior: "chase", elite: 0, xp: 10, count: 130, lv: 2,
      },
      goblin: {
        name: "Gobelin furtif", hp: 130, atk: 7, r: 20, speed: 88, aggro: 220,
        behavior: "skirmish", elite: 0, xp: 11, count: 110, lv: 3,
      },
      beetle: {
        name: "Carapace d'acier", hp: 380, atk: 12, r: 30, speed: 42, aggro: 240,
        behavior: "charge", elite: 0, xp: 18, count: 78, lv: 5,
      },
      wraith: {
        name: "Spectre des Portes", hp: 195, atk: 11, r: 22, speed: 62, aggro: 320,
        behavior: "kite", elite: 0, xp: 16, count: 72, lv: 6,
      },
      knight: {
        name: "Chevalier Noir", hp: 920, atk: 20, r: 38, speed: 48, aggro: 300,
        behavior: "brute", elite: 1, xp: 48, count: 42, lv: 9,
      },
    },

    GATES: [
      { x: 2800, y: 3200, rank: "E", color: "#5cff9a", sty: "beast", name: "Bête de Rang E", r: 98, hp: 2800, atk: 15 },
      { x: 18800, y: 3000, rank: "D", color: "#4aa3ff", sty: "wraith", name: "Gardien Azur", r: 98, hp: 3600, atk: 18 },
      { x: 3400, y: 18600, rank: "C", color: "#c56bff", sty: "spectre", name: "Spectre Royal", r: 98, hp: 4800, atk: 20 },
      { x: 18600, y: 18200, rank: "B", color: "#e7c56a", sty: "colossus", name: "Colosse d'Or", r: 98, hp: 6200, atk: 24 },
      { x: 11000, y: 5200, rank: "A", color: "#ff3355", sty: "tyrant", name: "Tyran Écarlate", r: 98, hp: 7800, atk: 28 },
      { x: 6200, y: 11000, rank: "B", color: "#e7c56a", sty: "colossus", name: "Colosse d'Ambre", r: 98, hp: 6200, atk: 24 },
      { x: 15800, y: 10800, rank: "A", color: "#ff3355", sty: "tyrant", name: "Tyran Cramoisi", r: 98, hp: 7800, atk: 28 },
    ],

    MINIS: [
      { x: 4500, y: 5400, rank: "E", color: "#5cff9a", sty: "beast", name: "Bête errante", hp: 2800, atk: 15 },
      { x: 8000, y: 2800, rank: "E", color: "#5cff9a", sty: "beast", name: "Alpha des landes", hp: 2800, atk: 15 },
      { x: 16500, y: 4800, rank: "D", color: "#4aa3ff", sty: "wraith", name: "Voile du Nord", hp: 3600, atk: 18 },
      { x: 20000, y: 7800, rank: "D", color: "#4aa3ff", sty: "wraith", name: "Gardien de Brume", hp: 3600, atk: 18 },
      { x: 2400, y: 8000, rank: "C", color: "#c56bff", sty: "spectre", name: "Spectre des Marais", hp: 4800, atk: 20 },
      { x: 9000, y: 16000, rank: "C", color: "#c56bff", sty: "spectre", name: "Héraut Violet", hp: 4800, atk: 20 },
      { x: 5000, y: 15000, rank: "B", color: "#e7c56a", sty: "colossus", name: "Colosse de Pierre", hp: 6200, atk: 24 },
      { x: 14000, y: 17000, rank: "B", color: "#e7c56a", sty: "colossus", name: "Colosse du Sud", hp: 6200, atk: 24 },
      { x: 17500, y: 14000, rank: "A", color: "#ff3355", sty: "tyrant", name: "Tyran des Cendres", hp: 7800, atk: 28 },
      { x: 7800, y: 7800, rank: "A", color: "#ff3355", sty: "tyrant", name: "Tyran de Granit", hp: 7800, atk: 28 },
      { x: 12800, y: 3600, rank: "D", color: "#4aa3ff", sty: "wraith", name: "Sentinelle Glacée", hp: 3600, atk: 18 },
      { x: 3600, y: 12000, rank: "C", color: "#c56bff", sty: "spectre", name: "Ombre du Ravine", hp: 4800, atk: 20 },
      { x: 20000, y: 16000, rank: "B", color: "#e7c56a", sty: "colossus", name: "Colosse d'Ivoire", hp: 6200, atk: 24 },
      { x: 9800, y: 19000, rank: "E", color: "#5cff9a", sty: "beast", name: "Bête du Cap", hp: 2800, atk: 15 },
    ],

    BATTLE_PASS: {
      season: "S1 — Armure & Ombre",
      note: "Armures, lames, tirs et ombres. Plus c’est stylé, plus ça se mérite.",
      levels: [
        { lv: 1, xp: 175, kind: "weapon", id: "sys_blue", name: "Lame Système", desc: "Cyan du Système." },
        { lv: 2, xp: 300, kind: "shot", id: "sys_blue", name: "Tir Système", desc: "Projectiles et sabre laser cyan." },
        { lv: 3, xp: 400, kind: "trail", id: "blot", name: "Petite ombre", desc: "Voile cyan qui te suit." },
        { lv: 4, xp: 725, kind: "weapon", id: "mana_violet", name: "Lame mana", desc: "Violet de chasseur." },
        { lv: 5, xp: 975, kind: "shot", id: "mana_violet", name: "Tir mana", desc: "Projectiles et sabre laser violet." },
        { lv: 6, xp: 1200, kind: "trail", id: "drip", name: "Double ombre", desc: "Deux voiles qui te suivent." },
        { lv: 7, xp: 1875, kind: "outfit", id: "abyss_ash", name: "Armure de Cendre", desc: "Plaques et pointes de fer." },
        { lv: 8, xp: 3000, kind: "weapon", id: "hunter_gold", name: "Lame d’or", desc: "Or de rang S." },
        { lv: 9, xp: 3750, kind: "shot", id: "hunter_gold", name: "Tir d’or", desc: "Projectiles et sabre laser or." },
        { lv: 10, xp: 4750, kind: "trail", id: "hex", name: "Ruban Système", desc: "Ruban cyan dans ton sillage." },
        { lv: 11, xp: 6750, kind: "outfit", id: "abyss_ember", name: "Armure de Braise", desc: "Fer noir, veines de feu." },
        { lv: 12, xp: 9500, kind: "weapon", id: "blood_red", name: "Lame écarlate", desc: "Rouge d’assassin." },
        { lv: 13, xp: 11000, kind: "shot", id: "blood_red", name: "Tir écarlate", desc: "Projectiles et sabre laser rouge." },
        { lv: 14, xp: 13125, kind: "trail", id: "wolf", name: "Spectre", desc: "Petite ombre fantôme." },
        { lv: 15, xp: 17500, kind: "outfit", id: "abyss_blood", name: "Armure Écarlate", desc: "Seigneur de guerre." },
        { lv: 16, xp: 23125, kind: "weapon", id: "arise_purple", name: "Lame Arise", desc: "Pourpre d’éveil." },
        { lv: 17, xp: 26250, kind: "shot", id: "arise_purple", name: "Tir Arise", desc: "Projectiles et sabre laser pourpre." },
        { lv: 18, xp: 30000, kind: "trail", id: "wings", name: "Nuée d’ombres", desc: "Plusieurs voiles autour de toi." },
        { lv: 19, xp: 38750, kind: "outfit", id: "abyss_gold", name: "Armure d’or noir", desc: "Filigrane d’or." },
        { lv: 20, xp: 50000, kind: "trail", id: "crown", name: "Voile d’or", desc: "Ombre dorée de rang S." },
        { lv: 21, xp: 63750, kind: "outfit", id: "abyss_night", name: "Armure de l’Abîme", desc: "Heaume cornu violet." },
        { lv: 22, xp: 81250, kind: "weapon", id: "monarch_ivory", name: "Lame Monarque", desc: "Ivoire et or." },
        { lv: 23, xp: 92500, kind: "shot", id: "monarch_ivory", name: "Tir Monarque", desc: "Projectiles et sabre laser ivoire." },
        { lv: 24, xp: 105000, kind: "trail", id: "eye", name: "Esprit Monarque", desc: "Ombre royale qui te suit." },
        { lv: 25, xp: 137500, kind: "outfit", id: "abyss_eye", name: "Regard de Malakor", desc: "Armure du Monarque, fente cyan." },
        { lv: 26, xp: 168750, kind: "trail", id: "divine_veil", name: "Auréole", desc: "Anneau d’or qui te suit." },
        { lv: 27, xp: 206250, kind: "weapon", id: "divine_sun", name: "Lame Divine", desc: "Blanc solaire, liseré d’or." },
        { lv: 28, xp: 231250, kind: "shot", id: "divine_sun", name: "Tir Divin", desc: "Projectiles et sabre laser solaire." },
        { lv: 29, xp: 250000, kind: "outfit", id: "divine_dawn", name: "Armure de l’Aube", desc: "Ivoire, halo d’or." },
        { lv: 30, xp: 306250, kind: "outfit", id: "divine_system", name: "Armure du Système", desc: "Blanc cyan, sceau divin." },
        { lv: 31, xp: 375000, kind: "outfit", id: "divine_monarch", name: "Armure Céleste", desc: "Ailes de lumière, jugement." },
      ],
      outfits: {
        abyss_ash: { form: "abyss", coat: "#16120e", head: "#1c1612", trim: "#8a7864", aura: "rgba(90, 70, 50, 0.42)", fx: "eye", visor: "#5ad4ff", spikes: 5 },
        abyss_ember: { form: "abyss", coat: "#120806", head: "#1a0c08", trim: "#c45a18", aura: "rgba(210, 70, 18, 0.52)", fx: "embers", visor: "#ff8020", spikes: 6 },
        abyss_blood: { form: "abyss", coat: "#0e0608", head: "#16080c", trim: "#9a1424", aura: "rgba(180, 16, 32, 0.52)", fx: "eye", visor: "#ff2038", spikes: 6 },
        abyss_gold: { form: "abyss", coat: "#100e0a", head: "#181410", trim: "#c4a050", aura: "rgba(190, 150, 40, 0.48)", fx: "crown", visor: "#ffe08a", spikes: 7 },
        abyss_night: { form: "abyss", coat: "#08060c", head: "#0c0814", trim: "#6a48b0", aura: "rgba(90, 40, 150, 0.5)", fx: "void", visor: "#c8b0ff", spikes: 7 },
        abyss_eye: { form: "abyss", coat: "#060408", head: "#0a0608", trim: "#5ad4ff", aura: "rgba(90, 212, 255, 0.5)", fx: "gaze", visor: "#9ef6ff", spikes: 8 },
        divine_dawn: { form: "divine", coat: "#efe6d2", head: "#f4ead8", trim: "#e7c56a", aura: "rgba(255, 220, 140, 0.55)", fx: "halo", visor: "#fff4c8", wings: 1 },
        divine_system: { form: "divine", coat: "#e8f6ff", head: "#f2fbff", trim: "#5ad4ff", aura: "rgba(140, 230, 255, 0.55)", fx: "halo", visor: "#9ef6ff", wings: 1 },
        divine_monarch: { form: "divine", coat: "#fff8ee", head: "#fffdf8", trim: "#ffe08a", aura: "rgba(255, 236, 180, 0.7)", fx: "seraph", visor: "#fff6d0", wings: 2 },
      },
      weapons: {
        sys_blue: { blade: "#5ad4ff", core: "#e8ffff" },
        mana_violet: { blade: "#9b8cff", core: "#e8e0ff" },
        hunter_gold: { blade: "#e7c56a", core: "#fff4c8" },
        blood_red: { blade: "#e23b4a", core: "#ffd0c8" },
        arise_purple: { blade: "#c56bff", core: "#f0d8ff" },
        monarch_ivory: { blade: "#efe7d6", core: "#fff8e8" },
        divine_sun: { blade: "#fff4c8", core: "#ffe08a" },
        cyan: { blade: "#5ad4ff", core: "#e8ffff" },
        crimson: { blade: "#e23b4a", core: "#ffd0c8" },
        gold: { blade: "#e7c56a", core: "#fff4c8" },
        void: { blade: "#efe7d6", core: "#ffffff" },
        ion: { blade: "#7cf0ff", core: "#f2ffff" },
      },
      shots: {
        sys_blue: { fx: "plasma", core: "#5ad4ff", glow: "rgba(90, 212, 255, 0.8)", hex: "#5ad4ff" },
        mana_violet: { fx: "plasma", core: "#9b8cff", glow: "rgba(155, 140, 255, 0.8)", hex: "#9b8cff" },
        hunter_gold: { fx: "comet", core: "#ffe08a", glow: "rgba(255, 200, 80, 0.8)", hex: "#e7c56a" },
        blood_red: { fx: "comet", core: "#ff4d5a", glow: "rgba(255, 50, 70, 0.8)", hex: "#e23b4a" },
        arise_purple: { fx: "rune", core: "#c56bff", glow: "rgba(197, 107, 255, 0.8)", hex: "#c56bff" },
        monarch_ivory: { fx: "comet", core: "#fff8e8", glow: "rgba(255, 240, 200, 0.85)", hex: "#efe7d6" },
        divine_sun: { fx: "plasma", core: "#fff4c8", glow: "rgba(255, 230, 140, 0.9)", hex: "#ffe08a" },
      },
      trails: {
        blot: { hex: "#5ad4ff", shape: "mist" },
        drip: { hex: "#6ee0ff", shape: "twin" },
        hex: { hex: "#5ad4ff", shape: "ribbon" },
        wolf: { hex: "#9b8cff", shape: "wraith" },
        wings: { hex: "#c56bff", shape: "swarm" },
        crown: { hex: "#e7c56a", shape: "goldveil" },
        eye: { hex: "#efe7d6", shape: "monarch" },
        glow: { hex: "#5ad4ff", shape: "mist" },
        gold: { hex: "#e7c56a", shape: "goldveil" },
        spectre: { hex: "#c8c4ff", shape: "wraith" },
        divine_veil: { hex: "#ffe08a", shape: "halo" },
      },
    },
  };
});
